/*
Copyright © 2025 NAME HERE <EMAIL ADDRESS>
*/
package cmd

import (
	"github.com/javsanmar5/stormy/utils"
	"github.com/spf13/cobra"
)

// newCmd represents the new command
var newCmd = &cobra.Command{
	Use:   "new",
	Short: "Create a new password generated by Stormy. ",
	Long: `Generate a good password automatically for a service and an user.

Example:
	# Generate a password for a github user
	stormy new -s github -u myuser`,

	Run: func(cmd *cobra.Command, args []string) {
		utils.NewPassword(service, username)
	},
}

func init() {
	rootCmd.AddCommand(newCmd)

	newCmd.Flags().StringVarP(&service, "service", "s", "", "Name of the service (required)")
	newCmd.Flags().StringVarP(&username, "username", "u", "", "Username for the service (required)")

	newCmd.MarkFlagRequired("service")
	newCmd.MarkFlagRequired("username")

}
